spring.application.name=Task Management
server.port=7082

#DataBase Connection
spring.data.mongodb.database=task_db

#Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:7111/eureka/
eureka.instance.hostname=localhost
eureka.instance.virtual-host-name=TASK-SVC

#JWT Secret Key